{{- if .Values.persistence.enabled -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
  labels:
    app: {{ .Values.service.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  encrypted: "true"
  iopsPerGB: "3000"
  throughput: "125"
allowVolumeExpansion: true
{{- end }}