apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
      nodePort: {{ .Values.api.service.nodePort }}