apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{.Values.service.ports.http}}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{.Values.service.ports.https}}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: {{ .Values.service.name }}