apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      app: ui
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: {{ .Values.ui.image }}
          ports:
            - containerPort: {{ .Values.ui.service.port }}
          env:
            - name: VITE_API_URL
              value: {{ .Values.ui.buildArgs.VITE_API_URL | quote }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.ui.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.ui.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
      volumes:
        - name: nginx-config
          configMap:
            name: ui-nginx-config