apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: ui
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: {{ .Values.ui.service.port }}
  type: {{ .Values.ui.service.type }}