replicaCount: 1

image:
  repository: umesh3149044/ui
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: ui
  type: ClusterIP
  port: 80

# UI specific configuration
config:
  apiUrl: "/api"  # This will be prefixed to /api/events in the UI code

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

ingress:
  enabled: true
  className: "nginx"