image:
  repository: arm64v8/postgres
  tag: 15.3-alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432
  name: postgres

persistence:
  enabled: true
  defaultClass: false
  reclaimPolicy: Delete
  storageClass:
    # If empty, will create and use the Release-specific StorageClass
    name: ""
    # Using gp3 for better performance/cost ratio
    type: gp3
    # Minimum IOPS for gp3
    iops: "3000"
    # Minimum throughput for gp3
    throughput: "125"
  # Reduced size for demo
  size: 1Gi

environment: Development

database:
  name: eventbooking
  user: postgres
  secret:
    name: db-credentials
    passwordKey: password

# Reduced resource limits for demo
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

securityContext:
  fsGroup: 999