image:
  repository: postgres
  tag: 15.3-alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432
  name: postgres

persistence:
  enabled: true
  storageClass: "ebs-sc"
  size: 1Gi  # Minimum size for demo

database:
  name: eventbooking
  user: postgres
  secret:
    name: db-credentials
    passwordKey: password

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

securityContext:
  fsGroup: 999

# Tolerations to run on tainted nodes
tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "karpenter.sh/disrupted"
    operator: "Exists"
    effect: "NoSchedule"