replicaCount: 1

image:
  repository: umesh3149044/api
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    http: 5000
  name: api

# API specific configuration
config:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: "http://*:5000"  # Only use HTTP
  AllowedOrigins__0: "http://localhost,http://a54d18af601a34b5da76123105669221-641622017.ap-south-1.elb.amazonaws.com"  # Match ingress host

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi